services:
  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    ports:
      - "8080:80"
    environment:
      - AP_ENVIRONMENT=prod
      - AP_REDIS_TYPE=MEMORY
      - AP_DB_TYPE=PGLITE
      - AP_FRONTEND_URL=http://172.30.164.146:8080
    volumes:
      - ./ap_data:/root/.activepieces
    restart: always